import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/Components/Common/Navbar";
import Footer from "@/Components/Common/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="">   <Navbar />
      {children}
      <Footer /></div>
  );
}
